### PR TITLE
removed tuid from dataprovider for test

### PR DESCRIPTION
**Pull request by vdelendik**

### CODE REVIEW

**Comment by vdelendik** [comment]
Can one of the admins verify this patch?

**Comment by ilya-varchenya** [comment]
comment

**Comment by vdelendik** [comment]
There were no errors, go have a cup of coffee...

**Comment by vdelendik** [comment]
There were no errors, go have a cup of coffee...

**Comment by vdelendik** [comment]
There were no errors, go have a cup of coffee...

**Comment by vdelendik** [comment]
There were no errors, go have a cup of coffee...

**Pull request closed without merging**
